project:
  type: website
  output-dir: C:\Users\Muhammad Jayadi\Documents\GitHub\E-Portfolio

website:
  title: "Muhammad Jayadi | E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

